# Render.com Deployment Configuration
# This file tells Render how to run your app

services:
  # Web Service
  - type: web
    name: nonprofit-platform
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nonprofit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: false

databases:
  - name: nonprofit-db
    databaseName: nonprofits
    plan: free
